# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/support/hello_world/service.proto

require 'google/protobuf'


descriptor_data = "\n&spec/support/hello_world/service.proto\"+\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x03(\t\"\x1e\n\x0eGoodbyeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x0fGoodbyeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloRequest").msgclass
HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloResponse").msgclass
GoodbyeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GoodbyeRequest").msgclass
GoodbyeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GoodbyeResponse").msgclass
