name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ 3.1, 3.0, 2.7 ]
        twirp-version: [ 1.9, ">= 1.10" ]

    name: Ruby ${{ matrix.ruby-version }} x Twirp ${{ matrix.twirp-version }}

    steps:
      - name: clone ${{ github.repository }}
        uses: actions/checkout@v3
      - name: setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          # bundler-cache: true
      - name: Bundle install
        env:
          TWIRP_VERSION: ${{ matrix.twirp-version }}
        run: bundle update twirp
      - name: run tests
        run: bundle exec rspec
      - name: upload code coverage
        uses: codecov/codecov-action@v3
